version: "3.7"

services:
  vue:
    image: silverstack19/frontend:latest
    ports:
      - "80:80"
    environment:
      - VUE_APP_MAIN_URL= 'http://3.236.92.142/product/'
    networks:
      - simplenet

networks:
  simplenet:
